/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_facere1_code_facere1_MainActivity */

#ifndef _Included_com_facere1_code_facere1_MainActivity
#define _Included_com_facere1_code_facere1_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_facere1_code_facere1_MainActivity
 * Method:    ImgFun
 * Signature: (Ljava/lang/String;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_com_facere1_code_facere1_MainActivity_ImgFun
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
